function [acc,p] = Clicks_Bounded_Accumulator_Accuracy_Interrogation(rp,rm,beta)
n = -beta:beta;
qp = (rm+rm^2+rp+rp^2+sqrt(-4*rm^2*rp^2+(rm+rm^2+rp+rp^2)^2))/(2*rp*rm);
qm = (rm+rm^2+rp+rp^2-sqrt(-4*rm^2*rp^2+(rm+rm^2+rp+rp^2)^2))/(2*rp*rm);

C1 = -(((-1 + qm)*qm^(1 + beta)*(-1 + qp)*(-qm^(-beta) + qm^beta*(1 + rm) -... 
    qm^(-1 + beta)*rp)*(-(qp*(1 - qp^(2*beta) - qp*rm + rp)*...
      (qm - qm^(1 + 2*beta)*(1 + rm) + qm^(2*beta)*rp)) +... 
    qm*(1 - qm^(2*beta) - qm*rm + rp)*(qp - qp^(1 + 2*beta)*(1 + rm) +... 
      qp^(2*beta)*rp)))/((-1 + qp)*(qm*(-1 + qm^(1 + 2*beta))*(rm - rp) -... 
     (1 + 2*beta)*(1 - qm)*(qm - qm^(1 + 2*beta)*(1 + rm) + qm^(2*beta)*rp))*...
    (-(qp*(1 - qp^(2*beta) - qp*rm + rp)*(qm - qm^(1 + 2*beta)*(1 + rm) +... 
        qm^(2*beta)*rp)) + qm*(1 - qm^(2*beta) - qm*rm + rp)*...
      (qp - qp^(1 + 2*beta)*(1 + rm) + qp^(2*beta)*rp)) -... 
   (-qm + qm^(2*beta))*(rm - rp)*(qm*rm - rp)*(qm^2*(qp - qp^(2 + 2*beta)) +... 
     qm^(2*beta)*qp*(-1 + qp^(1 + 2*beta))*rp - qm^(1 + 2*beta)*qp*...
      (-1 + qp^(1 + 2*beta))*(1 + rm + rp) +... 
     qm*(-qp^2 + qp^(2 + 2*beta)*(2 + rm) + qp^(2*beta)*rp -... 
       qp^(1 + 2*beta)*(1 + rm + rp)) + qm^(2 + 2*beta)*...
      (qp^2 - qp*(2 + rm) - qp^(2*beta)*rp + qp^(1 + 2*beta)*(1 + rm + rp)))));

C2 = -(((-1 + qm)*(qm - qm^(2*beta))*(-1 + qp)*qp^(1 + beta)*(rm - rp)*...
   (qm*rm - rp))/(-(qm^(2*beta)*qp*rp*(1 - qp^(2*beta) + rm + qp^2*rm +... 
      2*beta*(-1 + qp)*(-1 + qp^(2*beta) + qp*rm - rp) +... 
      qp^(1 + 2*beta)*(1 - rm + rp) - qp*(1 + rm + rp))) +... 
   qm^3*rm*(-((1 + 2*beta)*qp^2) + qp*(1 + 2*beta + rm - rp) +... 
     (1 + 2*beta)*qp^(2*beta)*rp - (1 + 2*beta)*qp^(1 + 2*beta)*...
      (1 + rm + rp) + qp^(2 + 2*beta)*(1 + 2*beta*(1 + rm) + rp)) +... 
   qm^2*(qp^3*(rm + 2*beta*rm) - (1 + 2*beta)*qp^(2*beta)*rp*(1 + rm + rp) -... 
     qp*(rm + 2*beta*rm + rm^2 - rp^2) + (1 + 2*beta)*qp^(1 + 2*beta)*...
      (rm^2 + 2*rm*(1 + rp) + rp*(2 + rp)) - qp^(2 + 2*beta)*...
      (2*beta*rm^2 + (1 + 2*beta)*rm*(2 + rp) + rp*(1 + 2*beta + rp))) -... 
   qm^(2 + 2*beta)*(-(qp^(2*beta)*rp*(1 + 2*beta - rm + rp)) +... 
     qp^3*rm*(1 + 2*beta*(1 + rm) + rp) + qp^(1 + 2*beta)*...
      (-rm^2 + rp*(1 + 2*beta + rp)) -... 
     qp^2*(2*beta*rm^2 + (1 + 2*beta)*rm*(2 + rp) + rp*(1 + 2*beta + rp)) +... 
     qp*(rm^2 + rp*(1 + 2*beta + rp) + rm*(1 - rp + 2*beta*(1 + rp)))) +... 
   qm^(1 + 2*beta)*(-((1 + 2*beta)*qp^(2*beta)*rp) +... 
     (1 + 2*beta)*qp^3*rm*(1 + rm + rp) - (1 + 2*beta)*qp^2*...
      (rm^2 + 2*rm*(1 + rp) + rp*(2 + rp)) + qp^(2 + 2*beta)*...
      (-rm^2 + rp*(1 + 2*beta + rp)) + qp*(rm^2 + (1 + 2*beta)*rm*(1 + rp) +... 
       2*rp*(1 + beta*(2 + rp)))) + qm*(-(qp^3*rm*(1 + 2*beta + rm - rp)) +... 
     qp^2*(rm + 2*beta*rm + rm^2 - rp^2) + qp^(2*beta)*rp*...
      (1 + rm + 2*beta*(1 + rp)) + qp^(2 + 2*beta)*...
      (rm^2 + rp*(1 + 2*beta + rp) + rm*(1 - rp + 2*beta*(1 + rp))) -... 
     qp^(1 + 2*beta)*(rm^2 + (1 + 2*beta)*rm*(1 + rp) +... 
       2*rp*(1 + beta*(2 + rp))))));

C3 = -(((-1 + qm)*qm^(1 + beta)*(-1 + qp)*(qp - qp^(2*beta))*(rm - rp)*...
   (qp*rm - rp))/(qm^(2*beta)*qp*rp*(1 - qp^(2*beta) + rm + qp^2*rm +... 
     2*beta*(-1 + qp)*(-1 + qp^(2*beta) + qp*rm - rp) +... 
     qp^(1 + 2*beta)*(1 - rm + rp) - qp*(1 + rm + rp)) -... 
   qm^3*rm*(-((1 + 2*beta)*qp^2) + qp*(1 + 2*beta + rm - rp) +... 
     (1 + 2*beta)*qp^(2*beta)*rp - (1 + 2*beta)*qp^(1 + 2*beta)*...
      (1 + rm + rp) + qp^(2 + 2*beta)*(1 + 2*beta*(1 + rm) + rp)) +... 
   qm^2*(-(qp^3*(rm + 2*beta*rm)) + (1 + 2*beta)*qp^(2*beta)*rp*...
      (1 + rm + rp) + qp*(rm + 2*beta*rm + rm^2 - rp^2) -... 
     (1 + 2*beta)*qp^(1 + 2*beta)*(rm^2 + 2*rm*(1 + rp) + rp*(2 + rp)) +... 
     qp^(2 + 2*beta)*(2*beta*rm^2 + (1 + 2*beta)*rm*(2 + rp) +... 
       rp*(1 + 2*beta + rp))) + qm^(2 + 2*beta)*...
    (-(qp^(2*beta)*rp*(1 + 2*beta - rm + rp)) +... 
     qp^3*rm*(1 + 2*beta*(1 + rm) + rp) + qp^(1 + 2*beta)*...
      (-rm^2 + rp*(1 + 2*beta + rp)) -... 
     qp^2*(2*beta*rm^2 + (1 + 2*beta)*rm*(2 + rp) + rp*(1 + 2*beta + rp)) +... 
     qp*(rm^2 + rp*(1 + 2*beta + rp) + rm*(1 - rp + 2*beta*(1 + rp)))) -... 
   qm^(1 + 2*beta)*(-((1 + 2*beta)*qp^(2*beta)*rp) +... 
     (1 + 2*beta)*qp^3*rm*(1 + rm + rp) - (1 + 2*beta)*qp^2*...
      (rm^2 + 2*rm*(1 + rp) + rp*(2 + rp)) + qp^(2 + 2*beta)*...
      (-rm^2 + rp*(1 + 2*beta + rp)) + qp*(rm^2 + (1 + 2*beta)*rm*(1 + rp) +... 
       2*rp*(1 + beta*(2 + rp)))) - qm*(-(qp^3*rm*(1 + 2*beta + rm - rp)) +... 
     qp^2*(rm + 2*beta*rm + rm^2 - rp^2) + qp^(2*beta)*rp*...
      (1 + rm + 2*beta*(1 + rp)) + qp^(2 + 2*beta)*...
      (rm^2 + rp*(1 + 2*beta + rp) + rm*(1 - rp + 2*beta*(1 + rp))) -... 
     qp^(1 + 2*beta)*(rm^2 + (1 + 2*beta)*rm*(1 + rp) +... 
       2*rp*(1 + beta*(2 + rp))))));

p = C1+C2*qp.^n+C3*qm.^(-n);
acc = sum(p(n>=0));